server:
  port: 8090

spring:
  application:
    name: gateway-service
  eureka:
    client:
      service-url:
        defaultZone: http://localhost:8761/eureka
    instance:
      prefer-ip-address: true
      hostname: localhost
  cloud:
    gateway:
      routes:
        - id: customer
          uri: lb://CUSTOMER
          predicates:
            - Path=/api/v1/customers/**
          filters:
            - CustomFilter
        - id: fraud
          uri: lb://FRAUD
          predicates:
            - Path=/api/v1/fraud-check/**
          filters:
            - CustomFilter

