server:
  port: 8080

spring:
  application:
    name: customer
  datasource:
    url: jdbc:h2:mem:navin
    platform: h2
  jpa:
    defer-datasource-initialization: true
    show-sql: true
  h2:
    console.enabled: true

  eureka:
    client:
      service-url:
        defaultZone: http://localhost:8761/eureka
      fetch-registry: true
      register-with-eureka: true
    instance:
      prefer-ip-address: true
      hostname: localhost